spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_app
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#      private static  String DRIVER_NAME = "com.mysql.cj.jdbc.Driver";
#      private static  String URL = "jdbc:mysql://localhost:3306/crm_app";
#      private static  String USER_NAME = "root";
#      private static  String PASSWORD = "123";
